name: PMA CI
on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  Readiness-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.x
          cache: npm

      - name: Install modules
        run: npm install

      - name: Linter
        run: npm run lint

      - name: Style
        run: npm run style

      - name: Build
        run: npm run build

      # - name: Jest-Test
      #   run: npm run test


